platform :ios, '9.0'

inhibit_all_warnings!

use_frameworks!

def shared_pods
  
  # Analytics
  
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  
  # Database
  
  pod 'RealmSwift'
  
  # Network
  
  pod 'Alamofire'
  pod 'AlamofireNetworkActivityIndicator'
  pod 'Kingfisher'
  
  # ReCaptcha
  
  pod 'ReCaptcha'
  
  # UI
  
  pod 'SwiftEntryKit', '1.0.1'
  
  # Utils
  
  pod 'PhoneNumberKit'
  pod 'XCGLogger', '~> 6.1.0'

end

target 'MUSwiftFramework' do
  
    shared_pods
    
end

target 'MUViper' do
  
    shared_pods
    
    # Dependency Injection
    
    pod 'Swinject'
    pod 'SwinjectStoryboard'
    
    # UI
    
    pod 'SwiftEntryKit', '1.0.1'
    
end
